<project>
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.cavetale.pom</groupId>
    <artifactId>cavetale-pom-base</artifactId>
    <version>0.1-SNAPSHOT</version>
  </parent>

  <groupId>com.winthier.connect</groupId>
  <artifactId>connect</artifactId>
  <version>0.1-SNAPSHOT</version>

  <name>Connect</name>
  <url>https://github.com/StarTux/Connect</url>
  <packaging>jar</packaging>

  <build>
    <plugins>

      <!-- Shade -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <artifactSet>
                <includes>
                  <include>com.winthier.connect:connect-core</include>
                </includes>
              </artifactSet>
              <filters>
                <filter>
                  <artifact>com.winthier.connect:connect-core</artifact>
                  <includes>
                    <include>**/*.class</include>
                  </includes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>

  <dependencies>

    <!-- Paper API -->
    <dependency>
      <groupId>io.papermc.paper</groupId>
      <artifactId>paper-api</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- Connect-Core -->
    <dependency>
      <groupId>com.winthier.connect</groupId>
      <artifactId>connect-core</artifactId>
      <version>0.1-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>

    <!-- Lombok -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- Core -->
    <dependency>
      <groupId>com.cavetale.core</groupId>
      <artifactId>core</artifactId>
      <version>0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>

  </dependencies>
</project>
