name: Connect
description: Connect Nukkit and Bukkit servers
author: StarTux
version: "0.1"
api: ["1.0.8"]
website: https://cavetale.com
main: com.winthier.connect.ConnectPlugin
depend: [Redis]
commands:
  connect:
    description: Admin interface
    permission: connect.connect
    usage: |-
      /connect status
      /connect reload
      /connect ping
      /connect debug
      /connect players
      /connect packet <to> <chan> <payload...>
#  remote:
#    aliases: [game, games]
#    description: Remote command interface
#    permission: connect.remote
#    usage: /remote ...
permissions:
  connect.connect:
    description: Use the /connect command
    default: op
  connect.remote:
    description: Use the /remote command
    default: op