name: Connect
description: Connect Bukkit servers
author: StarTux
version: 0.1
main: com.winthier.connect.bukkit.BukkitConnectPlugin
depend: []
commands:
  connect:
    description: Admin interface
    permission: connect.connect
    usage: |-
      /<command> status
      /<command> reload
      /<command> ping
      /<command> debug
      /<command> players
      /<command> packet <to> <chan> <payload...>
  remote:
    description: Remote command interface
    permission: connect.remote
    usage: /<command> ...
permissions:
  connect.connect:
    description: Use the /connect command
    default: op
  connect.remote:
    description: Use the /remote command
    default: op